[package]
name = "dtbur/ffg-idle-roblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
directory = "/Packages"

[dependencies]
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Find = "sleitnick/find@1.0.0"
Sift = "csqrl/sift@0.0.11"
Trove = "sleitnick/trove@1.5.1"
uilabs = "pepeeltoro41/ui-labs@2.4.1"
satchel = "ryanlua/satchel@1.0.0"