[package]
name = "ffg/game"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
private = true

[dependencies]
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Find = "sleitnick/find@^1.0.0"
Sift = "csqrl/sift@^0.0.11"
Trove = "sleitnick/trove@^1.5.1"
Uilabs = "pepeeltoro41/ui-labs@^2.4.1"
Satchel = "ryanlua/satchel@^1.0.0"
React = "jsdotlua/react@^17.2.1"
React-roblox = "jsdotlua/react-roblox@17.2.1"
React-charm = "littensy/react-charm@0.3.0"
Charm = "littensy/charm@0.10.0"
CharmSync = "littensy/charm-sync@0.3.0"
ByteNet = "ffrostflame/bytenet@^0.4.6"
Ripple = "littensy/ripple@0.10.0"